% This compile.m is used under Linux
clc;
clear mex
fprintf('Compiling S-UNIWARD ... ');

%% 64 bit Windows and Matlab
mex -O -largeArrayDims -output S_UNIWARD ...
    -I../include ...
    S-UNIWARD_matlab.cpp ...
    cost_model_config.cpp ... 
    cost_model.cpp ...    
    ../include/base_cost_model.cpp ...
    ../include/base_cost_model_config.cpp ...
    ../include/mi_embedder.cpp ...
    ../include/stc_ml_c.cpp ...
    ../include/stc_embed_c.cpp ...
    ../include/stc_extract_c.cpp ...
    ../include/common.cpp ...
    ../include/image.cpp ...
    ../include/info_theory.cpp

fprintf('DONE\n');
clear mex
movefile('*.mex*','../matlab/matlab_MEX');
fprintf('\nCompiled S-UNIWARD MEX file was moved to ../matlab/matlab_MEX folder.\n');
