% This compile.m is used under Windows
clc;
clear mex
fprintf('Compiling WOW ... ');

%% 64 bit Windows and Matlab
mex -O -largeArrayDims -output WOW ...
    -I../include ...
    WOW_matlab.cpp ...
    cost_model_config.cpp ... 
    cost_model.cpp ...    
    ../include/base_cost_model.cpp ...
    ../include/base_cost_model_config.cpp ...
    ../include/mi_embedder.cpp ...
    ../include/stc_ml_c.cpp ...
    ../include/stc_embed_c.cpp ...
    ../include/stc_extract_c.cpp ...
    ../include/common.cpp ...
    ../include/image.cpp ...
    ../include/info_theory.cpp ...

fprintf('DONE\n');
clear mex
movefile('*.mex*','../matlab/matlab_MEX');
fprintf('\nCompiled WOW MEX file was moved to ../matlab/matlab_MEX folder.\n');
